### ISSUE TITLE
automl does not have model_id arg

### ISSUE THREAD

**Issue by hiltbrd** [stevenpawley/h2oparsnip#2]
I was trying to use the automl feature of your package but kept getting the error: 

```r
> aml <- automl(mode = "regression") 
> aml %>% 
+   fit(mpg ~ ., data = mtcars)
Registered S3 method overwritten by 'data.table':
  method           from
  print.data.table     
  |===========================================================================| 100%
Error in h2o::h2o.automl(x = c("cyl", "disp", "hp", "drat", "wt", "qsec",  : 
  unused argument (model_id = "automl_904723902")
Timing stopped at: 0.48 0.036 0.594
```

I checked the docs and it looks like h2o does not use model_id with their automl function.
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/algo-params/model_id.html?highlight=model_id

**Comment by stevenpawley** [comment]
Thanks for reporting this, the `automl` model is so far just a quick/rough addition and I assumed that it also had a `model_id` - fixed in recent commits.
