### ISSUE TITLE
Error installing the package : Error: package or namespace load failed for 'h2oparsnip':

### ISSUE THREAD

**Issue by manher1992** [stevenpawley/h2oparsnip#3]
Hey, During the installation I get the error : 

** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'h2oparsnip':
 .onLoad failed in loadNamespace() for 'h2oparsnip', details:
  call: NULL
  error: The values passed to `set_encoding()` are missing arguments: 'compute_intercept', 'remove_intercept'
Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed
* removing '..:/Users/UserName/Documents/R/win-library/3.6/h2oparsnip'
Error: Failed to install 'h2oparsnip' from GitHub:
  (converted from warning) installation of package ‘C:/..... h2oparsnip_0.1.0.tar.gz’ had non-zero exit status

Do you have any idea where this error comes from ?

**Comment by stevenpawley** [comment]
Thanks for reporting. Looks like recent changes with parsnip have caused the issue - some additional encoding options were added to parsnip to specify how each model_spec deals with encoding factor variables. I'll update h20parnip later today to accommodate this.

**Comment by manher1992** [comment]
Let me know when I can try again. I'll test it right away.

**Comment by stevenpawley** [comment]
It should be fixed and updated now to reflect the new encoding options in parsnip.

**Comment by manher1992** [comment]
Thank you, it works.
